# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master



jobs: 
  - job: build_containers
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: docker-compose build
      displayName: 'Build Containers'
    - script: | 
        mkdir "publish" && \
        docker save -o ./publish/docker-images.tar express-api:latest vue-client:latest
      displayName: 'save docker image'
    - task: PublishPipelineArtifact@0
      inputs: 
        artifactName: images
        targetPath: './publish'
  - job: vulnerability_scanning_vue_client
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          cd vue-client
          npm ci
          npx snyk auth
          npx snyk test
        env: 
          SNYK_TOKEN: $(SNYK_TOKEN)
  - job: vulnerability_scanning_express_api
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          cd express-api
          npm ci
          npx snyk auth
          npx snyk test
        env: 
          SNYK_TOKEN: $(SNYK_TOKEN)
  - job: integration_tests
    pool:
      vmImage: 'Ubuntu-16.04'
    dependsOn: 
      - build_containers
    steps:
      - task: DownloadPipelineArtifact@0
        inputs: 
          targetPath: .
          artifactName: images
      - script: docker load < docker-images.tar
        displayName: 'Loading Docker Images'
      - script: docker-compose up -d
        displayName: 'Start Backend'